#!/bin/bash
cc  mal_test_0.c    -o ./bin/mal_test_0        -Wall -ldl -lpthread -lm
c++ mal_test_0.c    -o ./bin/mal_test_0_cpp    -Wall -ldl -lpthread -lm

cc  mal_profiling.c -o ./bin/mal_profiling     -Wall -ldl -lpthread -lm -mfpu=neon -O2
c++ mal_profiling.c -o ./bin/mal_profiling_cpp -Wall -ldl -lpthread -lm -mfpu=neon -O2

cc  mal_dithering.c -o ./bin/mal_dithering     -Wall -ldl -lpthread -lm
c++ mal_dithering.c -o ./bin/mal_dithering_cpp -Wall -ldl -lpthread -lm