name: ci

on:
  push:
  pull_request:

jobs:
  test:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
      - name: install dependencies
        run: |
          sudo apt-get update && \
          sudo DEBIAN_FRONTEND=noninteractive \
          apt-get install -y --no-install-recommends \
          ca-certificates clang-15 clang-format-15 clang-tidy-15
      - name: compile binary
        run: |
          cd examples/
          gcc -O3 -g -fPIC -Wall -Wextra -pedantic engine_hello_world.c -lm -o engine_hello_world
          ls -al engine_hello_world
      - name: compile binary with clang
        run: |
            cd examples/
            clang-15 -O3 -g -std=c99 -fPIC \
            -Wall \
            -Wextra \
            -Weverything \
            -Wno-cast-align \
            -Wno-conversion \
            -Wno-covered-switch-default \
            -Wno-disabled-macro-expansion \
            -Wno-documentation-deprecated-sync \
            -Wno-format-nonliteral \
            -Wno-missing-field-initializers \
            -Wno-padded \
            -Wno-reserved-id-macro \
            -Wno-sign-compare \
            -Wno-thread-safety-analysis \
            -Wno-type-limits \
            -Wno-unused-parameter \
            -Wno-used-but-marked-unused \
            -Wno-vla \
            -Wno-documentation-unknown-command \
            \
            -Wno-missing-variable-declarations \
            -Wno-missing-prototypes \
            -Wno-error=deprecated-declarations \
            -Wno-error=unused-macros \
            -Wno-error=float-equal \
            -Wno-error=cast-qual \
            -Wno-error=strict-prototypes \
            -Wno-error=gnu-statement-expression \
            -Wno-documentation \
            -Werror \
            engine_hello_world.c -lm -o engine_hello_world
            ls -al engine_hello_world
  compile:
    name: debian test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Run test
        uses: addnab/docker-run-action@v3
        with:
            image: debian:latest
            options: -v ${{ github.workspace }}:/work
            run: |
                apt-get update; DEBIAN_FRONTEND=noninteractive apt-get install -y gcc libpthread-stubs0-dev
                id;ls -al /work/;cd /work/examples/
                gcc -O3 -g -fPIC -Wall -Wextra -pedantic engine_hello_world.c -lm -o engine_hello_world
                ls -al engine_hello_world
